language: scala

jdk: oraclejdk8

scala:
  - 2.11.8
  - 2.12.2

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2

script:
  - sbt compile
  - sbt coverage test

after_success:
  - sbt coverageReport coveralls

